#默认使用配置
spring:
  profiles:
    active: dev

redis:
       # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
      database: 3
      # redis服务器地址（默认为localhost）
#        host: 10.1.0.50
      host: 127.0.0.1
      # redis端口（默认为6379）
      port: 6379
      # redis访问密码（默认为空）
      password: 123456
      # redis连接超时时间（单位为毫秒）
      timeout: 0
      # redis连接池配置
      pool:
          # 最大可用连接数（默认为8，负数表示无限）
          max-active: 8
          # 最大空闲连接数（默认为8，负数表示无限）
          max-idle: 8
          # 最小空闲连接数（默认为0，该值只有为正数才有作用）
          min-idle: 0
          # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
          max-wait: -1

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.hotsale.*.entity
  mapperLocations: classpath:mapper/*/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/hotsale
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    # 使用druid数据源
     #   type: com.alibaba.druid.pool.DruidDataSource